### ISSUE TITLE
[LibreElec Nexus] The extension sub menu does not works

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#112]
Pressing activation on the extension menu entry in the shutdown dialog (stop sub menu) does not works.
Kodi throw this error:

`2024-03-11 21:04:28.130 T:19076    info <general>: Activate of window '10040' refused because there are active modal dialogs`

**Comment by realcopacetic** [comment]
> Pressing activation on the extension menu entry in the shutdown dialog (stop sub menu) does not works.
> Kodi throw this error:
> 
> `2024-03-11 21:04:28.130 T:19076    info <general>: Activate of window '10040' refused because there are active modal dialogs`

Hi I think this is something that came up before that I thought I had fixed but maybe I didn't push the updated version to the official repo yet. Will need to check, but the cause seemed to be one of the following:

https://github.com/realcopacetic/skin.copacetic/issues/44
https://github.com/realcopacetic/skin.copacetic/issues/43

I'll try and get this updated everywhere asap but in the meantime two things to try:

1) skin.copacetic/shortcuts/Overrides.xml replace the 'O' with a lower case 'o' 

2) skin.copacetic/shortcuts/shutdownmenu.DATA.xml the <label>$LOCALIZE[24001]</label> should be replaced with <label>$LOCALIZE[10140]</label>

**Comment by pasnox** [comment]
renaming the override file fixed the issue, but cleared all my customization in the main menu.
I did change the localize number but I did not show any change.

**Comment by realcopacetic** [comment]
Marked as fixed, unfortunately removing/replacing overrides appears to reset the menu. Apologies for that

**Comment by pasnox** [comment]
This regressed in the last version.
I came back today and after automatic addon upgrade my main menu was reverted to the previous state and the shutdown menu would not allow extensions to open again.
