### ISSUE TITLE
[LibreElec Nexus] Can't access the shutdown menu with tv remote

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#113]
When using the tv remote it's not possible to reach the shutdown menu because long pressing back does not works with infra red, it seems that tv remote / hdmi CEC does not support concept of long / hold press.
I had to add a extension shortcut in the home menu, then browse my addons to select edit remote mapping to change the default shortcut to reach shutdown menu, just was annoying to do :/

**Comment by realcopacetic** [comment]
> When using the tv remote it's not possible to reach the shutdown menu because long pressing back does not works with infra red, it seems that tv remote / hdmi CEC does not support concept of long / hold press.
> I had to add a extension shortcut in the home menu, then browse my addons to select edit remote mapping to change the default shortcut to reach shutdown menu, just was annoying to do :/

Hi thanks for the feedback. Currently there are two options. 

1) You can add a shortcut directly to your main main menu, either for exit/shutdown or to open the while shutdown menu itself 'ActivateWindow(shutdownmenu)'

2) You can enable a shortcut in the hidden view types menu that is accessible with left/up press when browsing your media. This shortcut will open the shutdown menu and can be enabled in Copacetic settings

Do these do what you need or do you have another method in mind? One option would be a hidden home screen menu

**Comment by pasnox** [comment]
how do I reach the second idea?

**Comment by realcopacetic** [comment]
Settings > Copacetic > Views

It's at the top inter kiosk mode

**Comment by pasnox** [comment]
I must be dumb but I don't understand what you mean, could you detail the complete required steps?

**Comment by realcopacetic** [comment]
Sure thing, here you go:

Go to Settings > Copacetic > Views and enable the second option: 'Add shutdown menu shortcut to hidden views menu'

<img width="2560" alt="Screenshot 2024-03-18 at 12 57 42" src="https://github.com/realcopacetic/skin.copacetic/assets/14795443/fae8450a-f617-4797-b933-5e15035d88e4">

Now, when you are navigating your media in videos/music etc, if it is a vertically scrolling view, e.g. List or Grid, keep pressing left or keep pressing right until the hidden menu appears. Depending the view and what you have enabled, you may have to press it 2-3 times before the hidden menu is selected.

If it is a horizontally scrolling view, e.g. Billboard/Showcase/Strip, access it by pressing up or down until you see it.

Once you see it, it will look like this:

<img width="2560" alt="Screenshot 2024-03-18 at 13 19 50" src="https://github.com/realcopacetic/skin.copacetic/assets/14795443/bddb00ba-87a6-4ffc-948d-1e7ec61cf23a">

At the bottom, you should now have an extra item in the menu 'Shutdown menu' - clicking this will open the menu.

**Comment by pasnox** [comment]
ah, that explains things: I don't have this setting option 😂
Most likely the skin version is outdated from your repository.

**Comment by realcopacetic** [comment]
Ahh that will be why. I lost track of how old the version on Kodi official repo is. If you're happy to update from my third-party repo, you can get this and the fix for the overrides.xml file now. Otherwise I'll aim to get an update pushed to the official repo in the next couple of days!

**Comment by pasnox** [comment]
I switched to your repo and everything is fine now.
Some notes though, the switch to your repo was not smooth:
- the new version was not able to find its dependencies (the install dialog shows no dependencies at all) and I was left with the old version uninstalled and the new version not installed 
- this leads to Kodi not being able to switch to another theme as *none* was shown and triggering it lead to nothing
- I had to install all new dependencies manually before trying again to install the skin
- once everything was installed i had to reboot from ssh because for some reason the theme was not showing the main menu and only shown settings from the shutdown menu
- after the reboot everything works as expected - ouf 🥹

**Comment by realcopacetic** [comment]
That's strange, I've not seen that sort of behaviour before but haven't had a chance to test on LibreELEC. On my ShieldTV box, sometimes the update process can take a while and appear frozen on the current screen, or stuck on a black screen momentarily. But it will eventually sort itself. I've seen this behavior in updating Arctic Horizon 2 so I don't think it's an error, might just be if the code currently being displayed is touched by the update. But one time I quit out because I thought it had crashed and the update was a bit garbled so I had to delete the skin and start again. 

Please let me know if you have any other issues with updating. I'll be pushing an update to the kodi repo shortly if you prefer to switch back to the more stable version with less updates.
