### ISSUE TITLE
missing genre in media info

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#116]
Show media genre in media info

**Comment by realcopacetic** [comment]
Added in 1.1.20

**Comment by pasnox** [comment]
the media details page is now there and works, but the genre property is misnamed, see screenshot.

![IMG_20240327_145647.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/87e0ebd5-3681-4911-b816-e37852ffa04a)

**Comment by realcopacetic** [comment]
Thanks I will check it

**Comment by pasnox** [comment]
it seems to only appear when there is one genre only, when they are more it's correctly named

**Comment by realcopacetic** [comment]
Fixed in 1.1.25
