### ISSUE TITLE
Add media title in home screen

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#120]
The auto slideshow shown in the main menu  is great but quite limited, nobody knows every movie.
Sometimes I see a great screen but I have no idea which media it is.
In such a case, showing the media title in a corner would be helpful

**Comment by realcopacetic** [comment]
1.1.21 - Added a fallback label for when clearlogo is not present.

**Comment by pasnox** [comment]
just tested, does not work 😭
![IMG20240327121623.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/f402ab4e-7d96-4c31-840c-598eef96cbd3)

Here, there is no clear logo, nor movie title information. So if we saw a nice movie screen, then we don't know what it was

**Comment by pasnox** [comment]
just tested, does not work 😭
![IMG20240327121623.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/f402ab4e-7d96-4c31-840c-598eef96cbd3)

Here, there is no clear logo, nor movie title information. So if we saw a nice movie screen, then we don't know what it was

**Comment by realcopacetic** [comment]
Currently it is just during the 'screensaver' part once the menu is hidden. Would you like an option for it to show all the time?

There was also a bug in it I found last night

**Comment by pasnox** [comment]
yes, even in the non screensaver part that would be great, thanks

**Comment by realcopacetic** [comment]
Added in 1.1.25. To enable, go to Settings > Copacetic > Background > Enable 'Show the name of the current displayed background' to see a small label in the bottom left corner of all screens with background slideshows

**Comment by pasnox** [comment]
when will 1.1.25 be released?

**Comment by realcopacetic** [comment]
> when will 1.1.25 be released?

I'll try and push it to my repo tonight
