### ISSUE TITLE
Cleanup horizontal space in shutdown menu

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#121]
In LibreElec the shutdown menu is too verbose.
Please move LibreElec extension into settings and remove the useless quick theme switch.

![IMG20240318205526.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/a5ca9171-5194-4139-b099-66b317dc58e0)

**Comment by realcopacetic** [comment]
Useless? 😢

Updated in v1.1.20
- Added option to disable hardcoded shutdownmenu items (Home, Light/Night quick theme switcher, LibreELEC) in skin settings under Copacetic > General > Menus
- Added new LibreELEC shortcut in skin settings under Copacetic > General > Menus

**Comment by pasnox** [comment]
btw, is there a way to show the libreelec settings with themed components?
currently it shows up as with the estuary theme which does not fit nice

**Comment by realcopacetic** [comment]
I assume there is but I won't be able to do it without a LibreElec box to test and I don't have access to one unfortunately.

**Comment by realcopacetic** [comment]
Let me see if I can find any documentation for it

**Comment by realcopacetic** [comment]
Hi @pasnox  - it seems like this is not possible, according to the lIbreelec forums. Have you seen any skins that are able to do this? 

https://forum.libreelec.tv/thread/28345-libreelec-settings-screen-skinning/

**Comment by pasnox** [comment]
no, not really, i never used any other skin than the default estuary one before.
I can properly test starting Wednesday evening if needed.

**Comment by pasnox** [comment]
I just tested and indeed it keeps the same visual across all themes, let's forget this then.
