### ISSUE TITLE
Way to identify currently shown artwork

### ISSUE THREAD

**Issue by AllesMeins** [realcopacetic/skin.copacetic#124]
Sometimes I run into the situation that this great skin shows me an artwork and I think "wow that looks great" but have no idea what movie or show this is from. Is there a way to identify the artwork that is currently displayed? Either an option to just display the associated movie/show somewhere small in a corner or some button I could press to show some info on the currently displayed image (or even better: the last X displayed images in the case I've been to slow and the image has already changed)?

**Comment by realcopacetic** [comment]
Added in 1.1.25. To enable, go to Settings > Copacetic > Background > Enable 'Show the name of the current displayed background' to see a small label in the bottom left corner of all screens with background slideshows

**Comment by AllesMeins** [comment]
Thank you!

**Comment by realcopacetic** [comment]
> Thank you!

You're welcome I'll push the update to my repo in the next day or two
