### ISSUE TITLE
can't upgrade from libreelec copacetic to copacetic repo

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#126]
all dependencies versions clash and want to downgrade/ uninstall - themselves instead of upgrading.![IMG20240327115848.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/2e5b9335-d82a-460b-a973-c9df85658c2b)

![IMG20240327115838.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/011da276-77d6-49ab-bc92-5ea13550dd37)

**Comment by pasnox** [comment]
![IMG20240327120241.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/541456e4-db3c-4b56-9f6a-88961c2e2d43)

**Comment by realcopacetic** [comment]
Kodi Repo current minimum requirements are:
`<import addon="script.copacetic.helper" version="1.0.6" />`
`<import addon="resource.fonts.copacetic" version="1.0.2" />`
https://github.com/xbmc/repo-skins/blob/nexus/skin.copacetic/addon.xml

realcopacetic Repo current requirements are:
`<import addon="script.copacetic.helper" version="1.0.9" />`
`<import addon="resource.fonts.copacetic" version="1.0.4" />`
https://github.com/realcopacetic/skin.copacetic/blob/c91f0a64d125dde42ec4aa02b9e0df86307ab926/addon.xml

You're ahead of the minimum requirements anyway, so I'm not sure why it's not letting you do this.

I'm not sure why it's suggesting 1.0.8 and 1.0.2, it seems like an old version, can you force Kodi to check for addon updates?

Can I confirm you have these two options set under Settings > System > Addons:
- Enable Unknown Sources
- Update official addons from 'Any repositories'

If you have those, I would suggest switching to Estuary, uninstalling Copacetic skin in Addons, then choosing Install from Repository > and choosing realcopacetic Repository and installing it directly. Doing this should preserve any settings you've changed in the skin as I don't believe the file that saves this info is deleted when you uninstall an addon.

<img width="2478" alt="Screenshot 2024-03-27 at 12 06 12" src="https://github.com/realcopacetic/skin.copacetic/assets/14795443/d00251d9-f973-40ea-87aa-e1e3702a9e9f">

**Comment by pasnox** [comment]
ok, i only enabled updates from the official repo only.
So I was not able to go in your repo and install this version atop the already installed one.
Instead from the installed one from libreelec, going in its info, then versions I was able to select the non official version and upgrade went smoothly from there. I suppose the other way around it was not considered an upgrade and mess itself.
You can close the issue, thanks
