### ISSUE TITLE
Some Studio Logos are missing

### ISSUE THREAD

**Issue by PangolinWrestler** [realcopacetic/skin.copacetic#131]
Thanks for adding the other Studio Logos that i had reported missing over on the Kodi forum. Here are some more that are missing/not showing. Also, i noticed that the BBFC (UK) classification rating for 12A shows as 12. Not urgent. Whenever you have the time. The rest of the theme looks great! 

Xfilme
Epic Pictures
LD Entertainment
Filmdistrict
Roadside Attractions 
Vestron Pictures
New Century Entertainment Corp.
Bandai
Nikkatsu
Senator Entertainment
Month Python Pictures
Tele Munchen Gruppe (TMG)
Saban Films
Davis Films
Shochiku
LD Entertainment 
Baa-Ram-Ewe

**Comment by realcopacetic** [comment]
Currently doing this in the background to other things

- [X] Xfilme
- [x] Epic Pictures
- [X] LD Entertainment
- [x] Filmdistrict
- [X] Roadside Attractions 
- [x] Vestron Pictures
- [x] New Century Entertainment Corp.
- [x] Bandai
- [x] Nikkatsu
- [x] Senator Entertainment
- [ ] Month Python Pictures
- [x] Tele Munchen Gruppe (TMG)
- [x] Saban Films
- [x] Davis Films
- [X] Shochiku
- [X] LD Entertainment 
- [ ] Baa-Ram-Ewe
