### ISSUE TITLE
can't upgrade to latest release 

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#135]
We can't upgrade to latest release.
See screenshots.

![Screenshot_2024-04-03-19-31-56-48_1df7e81cb8b1830f43488e7a37ca3ed9.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/0ab22a32-2ab1-4a29-ae31-599829a10e0a)

**Comment by pasnox** [comment]
Kodi seems unable to download zip files. 
They do not appear in .kodi/addons/packages directory.

**Comment by pasnox** [comment]
I was able to upgrade by manually downloading all files from git and putting them in the packages directory.
The original issue remains though.

**Comment by realcopacetic** [comment]
I had to switch to using Git LFS as some of the zip files for the resources addon are too large. I must have done something wrong. I'll try and figure this out asap and push an update. Apologies for that!

**Comment by realcopacetic** [comment]
hi @pasnox - Hopefully this is fixed, please let me know if you have any issues grabbing 1.1.26. I just tested and I think it's working ok now

**Comment by pasnox** [comment]
1.1.26 went fine, thanks!
