### ISSUE TITLE
Missing OSD icons with Libreelec

### ISSUE THREAD

**Issue by pepszzi** [realcopacetic/skin.copacetic#137]
I've already tried a couple things. I also deinstalled the entire skin, include the settings and reinstalled it. Same result. 
When I downgrade to 1.1.16 the buttons back. 

I'm using the latest version 1.1.26 and I think this occurred with 1.1.22 or 1.1.23. 
Strangely, it works on my Android device. 
On this device (RPi 4) runs Libreelec, maybe that's the reason? Hope you can investigate further and please let me know if I can help. Thank you!

![image](https://github.com/realcopacetic/skin.copacetic/assets/99938783/035e889a-5aa4-4e2a-be29-8e7e60906f30)

![image](https://github.com/realcopacetic/skin.copacetic/assets/99938783/2e7913f0-f095-464b-8728-4021f04c2364)

**Comment by realcopacetic** [comment]
Fixed here wll push an updated version tonight - https://github.com/realcopacetic/skin.copacetic/commit/852ab523963c0a59dc0c68d71db1586ca7d2af8a
