### ISSUE TITLE
Widget subpage display bug

### ISSUE THREAD

**Issue by pepszzi** [realcopacetic/skin.copacetic#167]
When I open a widget that opens a subpage, something with the font is shifted:

![image](https://github.com/realcopacetic/skin.copacetic/assets/99938783/db00f020-46a8-4b78-8dcf-cafb153c6616)

![image](https://github.com/realcopacetic/skin.copacetic/assets/99938783/d9cc605f-aed6-4eaa-baa2-7b9b6c47c414)

**Comment by realcopacetic** [comment]
Thanks for flagging @pepszzi - figured out the issue and will try and push a fix this weekend. This will be fixed in 1.3.9

**Comment by realcopacetic** [comment]
Fixed in 1.3.9
