### ISSUE TITLE
Change text color in Strip view + small additions

### ISSUE THREAD

**Issue by Papitomalote** [realcopacetic/skin.copacetic#168]
Hello, thanks for the skin. Very intuitive and well thought. 
Is it possible to add a change color option for the strip view?. I prefer a white text instead of a blue one for example. 
And also, is it possible to add a smaller Grid view for huge collections? 
And finally, could you add a "Finishes in xx:xx pm", I find that information very useful and I saw it in other skins.

Thanks for your skin and the updates!

**Comment by realcopacetic** [comment]
Hi, thanks for the suggestions.
All three of these have been added into the upcoming version (2.4.3 for Omega and 1.4.3 for Nexus) which should be available from my repo in the next few days and from Kodi repo some time after

Ends time added to info screen in top right corner
Setting in Copacetic > Customisations to prefer white text for plots
Setting in Copacetic > Views to choose between small and large layouts for Grid view.
