### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ghost** [realcopacetic/skin.copacetic#173]
This skin has become my favorite Kodi skin, however I have some little suggestions to improve it. None of these should go against the simplicity this skin is aiming for.

**Video OSD:**
- When the video controls are shown, also show the video title somewhere on screen (maybe top right?)
- When using the arrow keys to fast forward or reverse in steps the popup that shows f.e. "+0:50" or "-08:20" etc. sometimes doesn't show up or fades away too quickly
- Add an option to show remaining time instead of length to the video progress bar
- Add an option to disable the "Movie title > video, audio codec > age rating" popup in the top left corner after starting a video
- Make the background for the OSD less dark. I sometimes like to pause and watch what is on screen, it's too dark to see anything

**List view:**
- Make very long titles scroll horizontally so you can read them completely, as of now they just stop with "..." when space runs out
- In episodes list view please add a fade between thumbnails if you scroll through episodes to keep it consistent with posters which have a fade

**Strip & showcase view:**
- An alternative color for the plot would be nice, preferably white instead of blue
- Add an option to show a checkmark instead of a progress bar for watched videos (like in grid view)

**Home menu:**
- If you install the skin there is no exit / shutdown menu option. I know you can add this by changing the home menu in general settings but for people trying the skin for the first time it might be good to have it by default

**Dialogue menus:**
- If you reach the top or bottom of the available options and press up or down again cycle back to beginning or end

**Comment by realcopacetic** [comment]
Hi thanks for all the suggestions, I'm glad you're enjoying it. During beta there weren't many users so it's a bit skewed right now to just how I do things. It's been good getting new perspectives since getting onto the official Kodi repo. 

I've started working on some of these but had some questions for you on a couple:

> If you install the skin there is no exit / shutdown menu option. I know you can add this by changing the home menu in general settings but for people trying the skin for the first time it might be good to have it by default

There should be an exit option by default on the shutdown menu which comes up if you hold back on the home screen or press s. Do you think this would be in the default main menu instead? 


> Dialogue menus:

> If you reach the top or bottom of the available options and press up or down again cycle back to beginning or end

Can you let me know where you saw this. I think I changed most of them to this behavior a whole ago but just have missed some

**Comment by ghost** [comment]
> There should be an exit option by default on the shutdown menu which comes up if you hold back on the home screen or press s. Do you think this would be in the default main menu instead?

I didn't know this. I just tried holding the back button on the home screen and it did indeed bring up the shutdown menu. Is this common knowledge? I'm using this skin on a Chromecast with a remote so I can't tell if keyboard shortcuts work since the remote only uses up/down/left/right, ok and back buttons. Imo it's better to show the end user all available menu options, it didn't cross my mind to hold the back button to bring up a different "hidden" shutdown menu.

> Can you let me know where you saw this. I think I changed most of them to this behavior a whole ago but just have missed some

For example: Hold the OK button on a movie in your library. This brings up a small menu.

Play
Play next
Queue item
Information
Mark as watched
Add to favorites
Play from here
Manage

Now if the "cursor" is on "Play" and I press up, it doesn't move all the way down to "Manage". There's no wraparound navigation between these options so to speak. That's no deal breaker just a little addition that'd be neat.

I am on copacetic version 1.3.1 from the official Kodi repo tho, I don't know if you've changed this behavior between this and the latest version of your repo.

**Comment by realcopacetic** [comment]
Hi, most of these should now be live in the version of my skin on my own repo (Omega: 2.4.3 / Nexus 1.4.3). I will submit it to the official Kodi repo, but I need to wait for them to approve an update to my helper addon first as the has dependencies on the latest version of that. So it may yet be a week or two depending on how quickly the approvals process happens by the Kodi team.

> When the video controls are shown, also show the video title somewhere on screen (maybe top right?)
Added in the top left, now the currently focused button label shows up as the secondary info label in the top left so it's like 
Title / Play, or Title / Fast forward etc.

> When using the arrow keys to fast forward or reverse in steps the popup that shows f.e. "+0:50" or "-08:20" etc. sometimes doesn't show up or fades away too quickly

I need to look into this one, but some of this behaviour is a core Kodi issue I believe as it's the same on the default skin Estuary (in my testing at least), where for up and down skips, the label clears very quickly. On the left/right skips, that's something I probably need to fix on myend.

> Add an option to show remaining time instead of length to the video progress bar

Added this option in Settings > Copacetic > Customisations > Video Player

> Add an option to disable the "Movie title > video, audio codec > age rating" popup in the top left corner after starting a video

Added this option in Settings > Copacetic > Customisations > Video Player

> Make the background for the OSD less dark. I sometimes like to pause and watch what is on screen, it's too dark to see anything

Will add an option for this in the next version

> List view:

> Make very long titles scroll horizontally so you can read them completely, as of now they just stop with "..." when space runs out

Added an option for this under Settings > Copacetic > Views > List

> In episodes list view please add a fade between thumbnails if you scroll through episodes to keep it consistent with posters which have a fade

Added this, thanks for pointing it out

> Strip & showcase view:

> An alternative color for the plot would be nice, preferably white instead of blue

Added this option under Settings > Copacetic > Customisations > Library

> Add an option to show a checkmark instead of a progress bar for watched videos (like in grid view)

Will need to figure this one out a bit more, how it's going to work, especially for strip, that view is manually built, which means I have to figure out all the animations for moving the checkmarks from one item to the next and then getting bigger smaller etc. Also I need to figure out where it would go / what it would look like

> Home menu:

> If you install the skin there is no exit / shutdown menu option. I know you can add this by changing the home menu in general settings but for people trying the skin for the first time it might be good to have it by default

I'm considering making an installation guide, either a Wiki or ideally something in Kodi the first time you run the skin. If I do, this will include guidance on access the hidden shutdown menu or adding your own shortcuts to the menu.

> Dialogue menus:

> If you reach the top or bottom of the available options and press up or down again cycle back to beginning or end

Added this

**Comment by ghost** [comment]
Thank you!
I've found one more issue:

In the customization settings the "Preferred classification ratings" menu shows completely different and unrelated options.

**Comment by realcopacetic** [comment]
> Thank you! I've found one more issue:
> 
> In the customization settings the "Preferred classification ratings" menu shows completely different and unrelated options.

AHH thanks yeah. I moved some labels around and forgot to update the numbers. Will get this fixed asap. Apologies for that. Are you using the skin from official Kodi repo or my repo?

**Comment by Dorro101** [comment]
Hi

Love your theme! It is my favourite so far by a country mile. Minimal, well designed, kind of Bauhaus. That said, is there any way to change the font? I like the font, but I have a licence to use HelveticaNeue (CorelDraw CD-ROM), which I think would rock the Bauhaus look. I have a few humble requests, as I know time is always an issue with projects like this, please do with it what you may, your hard work deserves that at least.

Showcase view

Is it possible to have an option make the artwork, in my case a poster, floating i.e. an equal border all around the edge matching the black (in this case) background?

Billboard view

Is it possible to have a left justified poster floating above the title, adjustable size would be awesome, on the series page. On the episodes page it would be nice to have a watched indicator. I personally like the little top right hand diagonal ribbon indicator in other themes that shows NEW, PAUSED (watching would make more sense to me, or busy or something) and WATCHED. I use the list view on the season page.

I use Kodi (at least my wife does, a lot, and I have mandatory TV time with her as she calls it) on a Rasberry PI 4 running LibreELEC. The only issue I have so far is the theme crashing Kodi to the loading screen, when I am toggling (up and down arrows on my remote, in the settings page, from Copacetic to Interface. If I find anything else I'll let you know.

Thank you again
Dorian

Oops, I just figured out what the indicator at the very bottom of the view indicated, obscure but cool! Tres minimalist, dig it. The number in a box spoils it a bit, maybe separate strips (thin elongated blogs?) the number of episodes correlating to the number of blobs and also could indicate watched status, position and unwatched using a progress blob, new could have a halo/glow dropshadow.
🤦‍♂️

**Comment by realcopacetic** [comment]
> Hi
> 
> Love your theme! It is my favourite so far by a country mile. Minimal, well designed, kind of Bauhaus. That said, is there any way to change the font? I like the font, but I have a licence to use HelveticaNeue (CorelDraw CD-ROM), which I think would rock the Bauhaus look. I have a few humble requests, as I know time is always an issue with projects like this, please do with it what you may, your hard work deserves that at least.
> 
> Showcase view
> 
> Is it possible to have an option make the artwork, in my case a poster, floating i.e. an equal border all around the edge matching the black (in this case) background?
> 
> Billboard view
> 
> Is it possible to have a left justified poster floating above the title, adjustable size would be awesome, on the series page. On the episodes page it would be nice to have a watched indicator. I personally like the little top right hand diagonal ribbon indicator in other themes that shows NEW, PAUSED (watching would make more sense to me, or busy or something) and WATCHED. I use the list view on the season page.
> 
> I use Kodi (at least my wife does, a lot, and I have mandatory TV time with her as she calls it) on a Rasberry PI 4 running LibreELEC. The only issue I have so far is the theme crashing Kodi to the loading screen, when I am toggling (up and down arrows on my remote, in the settings page, from Copacetic to Interface. If I find anything else I'll let you know.
> 
> Thank you again Dorian
> 
> Oops, I just figured out what the indicator at the very bottom of the view indicated, obscure but cool! Tres minimalist, dig it. The number in a box spoils it a bit, maybe separate strips (thin elongated blogs?) the number of episodes correlating to the number of blobs and also could indicate watched status, position and unwatched using a progress blob, new could have a halo/glow dropshadow. 🤦‍♂️

Thanks for the feedback and suggestions.

I can't legally package other fonts with the skin, have to use open source. But it is fairly straightforward for you to add your own font. I can tell you the steps to do it if you want, but the main issue I think you'll have is every time you update the skin, it would overwrite your changes. If you just want to see what it looks like though, I'll tell you what to edit.

**Showcase** / **Billboard** - Not planning to edit the views too much now as I want to clear some of the bugs and then start thinking about a new skin, but I'll keep a note of these requests for if I do have some time to revisit.

**Watched indicator** yes on most views the progress bar acts as the watched indicator as well, if it's completely full then it's watched. There's also a 'now playing' indicator if that's what you meant by 'watching'. The number in the box, do you mean the number of episodes left? You can turn that off in skin settings if that's what you meant.

** Crash ** Some other people have seen this same behaviour with LibreELEC, I'm not sure what's causing it and don't have a device to test it, but it seems related to this specific platform so I'm not sure if it's a memory issue. Each of those items in the settings menu is technically a different window. In the default skin, you go to a settings landing page then go into 'Interface', then go back to Settings and go into 'Media' etc. So if you scroll through the list in my view, where I've tried to make it feel like one window, it's actually scrolling through a bunch of different windows really quickly, which may be causing some sort of usage spike that causes the crash. Either that or I've got an obscure bug I haven;'t noticed yet

**Comment by Dorro101** [comment]
No worries! Thanks again for a stellar theme  and I'm looking forward to your next theme.

Ciao
Dorian
