### ISSUE TITLE
Feature Request: Option for brighter background images

### ISSUE THREAD

**Issue by va-lemon** [realcopacetic/skin.copacetic#175]
Currently, the options for background images on the Home Screen maxes out at 50. Could this option be expanded with brighter values?

Same request for the background image for item details pages (e.g. when viewing Movie or TV Show details). I have not found an option in Settings to adjust the brightness for background images on Detail views.

Amazing skin by the way!
Thanks

**Comment by realcopacetic** [comment]
Hey @va-lemon - thanks for the feedback. How bright are you looking to go? Another notch up or like all the way to 100?

**Comment by realcopacetic** [comment]
I've added the option to turn the brightness for infoscreen backgrounds higher in V2.5.0 (Omega) / V1.5.0 (Nexus). It will also be possible now to set home screen brightness higher than 50. This will go live on my repo shortly and on Kodi official repo in probably 1-2 weeks. Thanks
