### ISSUE TITLE
Weblate error

### ISSUE THREAD

**Issue by gade01** [realcopacetic/skin.copacetic#183]
https://github.com/realcopacetic/skin.copacetic/blob/d2af24436c85196f0bbbb627d53715dfc41d5eba/language/resource.language.en_gb/strings.po#L1015

You need 2 `""` on line 1015

**Comment by realcopacetic** [comment]
Thanks @gade01 - appreciate your help. I'll try not to mess up the weblate sync again!

**Comment by gade01** [comment]
Glad to help.
Please let me know if you have any questions:)

**Comment by realcopacetic** [comment]
Just one actually @gade01  - in the current pull request that has been opened: https://github.com/realcopacetic/skin.copacetic/pulls

I see a behaviour that keeps happening and I'm not sure if it's something I've done wrong. But if you look at the changed files e.g. the French description...

https://github.com/realcopacetic/skin.copacetic/pull/185/files

It wants to duplicate the text with carriage returns. You can see in the history of the translation on Weblate it keeps on happening...

https://kodi.weblate.cloud/translate/kodi-add-ons-skins/skin-copacetic/fr_fr/?&offset=2

Do you know what's going on?
