### ISSUE TITLE
Fast forward or jumping ahead in video will cause the jump ahead time displayed in the middle of the screen

### ISSUE THREAD

**Issue by GuidovMal** [realcopacetic/skin.copacetic#187]
When moving forward or jumping ahead in a video, the time you jumped ahead is displayed in the middle of the screen. It will not go away unless you stop and start the video again which is mildly annoying. 
See the attached screenshot where I forwarded and it shows +01:19 until I stopped the video and started again. It happens on all videos.

![1721697475795](https://github.com/user-attachments/assets/4cefa9b0-37b4-4e70-a542-8fb69da1e93f)

**Comment by realcopacetic** [comment]
Think I know what caused this. Will fix shortly thanks

**Comment by realcopacetic** [comment]
Fixed in 2.5.2

**Comment by GuidovMal** [comment]
Please forgive my ignorance but how do I set copatectic to update
automatically or even manually? I installed manually a while back due to
the kodi change to V21 where copatectic stopped working. I did try under
add-ons, my add-ons, copatectic, than auto update, but it always reverts
back to off.

Many thanks for the great work.

Guido
