### ISSUE TITLE
broken EPG in TV

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#192]
The TV view seems broken compared to the TV Guide view. The guide is Ok, but tv does miss most programs titles, and in some cases (France 2 here) show non matching EPG.

![IMG20240724232959.jpg](https://github.com/user-attachments/assets/08f068e8-f8b2-41e4-938a-235d8695fe3a)

![IMG20240724232933.jpg](https://github.com/user-attachments/assets/705d15b0-535d-428a-a0a0-0b8597b98255)

**Comment by realcopacetic** [comment]
hi, which addons do you use for live tv? I've just been using the free PlutoTV one that's in the Kodi repo to test, as I don't use PVR myself. This is what I see but it looks like most of the infor is missing for you, so I can try testing using the same one as you to see what's happening

<img width="1680" alt="Screenshot 2024-08-04 at 14 26 55" src="https://github.com/user-attachments/assets/ee5ef9c7-2de0-451f-a62b-6e03f4225955">

**Comment by pasnox** [comment]
I do use a mix of IPTV manager to get some channels from catch up tv coupled to pluto tv and Freebox PVR plugins.

**Comment by pasnox** [comment]
I had a closer look and it seems the issue is that you show the program sub title in the tv channels, which most of the time is missing.

In the guide we have that info:
- program name (1)
- program sub name (2, not always filled)
- program type (3)

In TV Channels we have that info:

on the left:
- title (2)
- type (3)

in the right:
- title (2)
- time
- type (3)

So you should use (1) instead of (2) on the left, and full (1), (2), (3) on the right.

**Comment by realcopacetic** [comment]
I've been working on some PVR updates, which should nown be live in my repo. Let me know if yuou still have problems. I haven't worked on the video osd yet, I still need to update a lot of the labels on things like the seekbar at the bottom and the file info label at the top but all the main PVR windows shoudl now be supported

**Comment by pasnox** [comment]
Epg is now fine in the tv channels.
thanks!
