### ISSUE TITLE
[Feature] option for auto hide osd (pause menu) after clicking play button

### ISSUE THREAD

**Issue by uaxpasha** [realcopacetic/skin.copacetic#193]
When you click play you need to press back so payse menu will hide. I suggest a feature where osd will auto hide after pressing play button. And configurable auto hide after 1-2-5-10 seconds for those whi want to see a frame without menu. Exceptional skin. One of the best, thank you.

**Comment by realcopacetic** [comment]
Hi, when you say 'pause menu' do you mean the controls (play button, back, forward, rewind etc)? Those should already auto-hide. Some others have had the issue where the OSD doesn't autohide, It seems confined to certain platforms, are you by any chance on LIbreElec?

**Comment by realcopacetic** [comment]
> When you click play you need to press back so payse menu will hide. I suggest a feature where osd will auto hide after pressing play button. And configurable auto hide after 1-2-5-10 seconds for those whi want to see a frame without menu. Exceptional skin. One of the best, thank you. 

Can you let me know if this still isn't auto closing in 2.6.0 please.

**Comment by uaxpasha** [comment]
> Hi, when you say 'pause menu' do you mean the controls (play button, back, forward, rewind etc)? Those should already auto-hide. Some others have had the issue where the OSD doesn't autohide, It seems confined to certain platforms, are you by any chance on LIbreElec?

No I don't use LIbreElec
I use Kodi on TCL Google TV and hands down copacetic is best looking interface list for movies and billboard for TV show I ever seen whether it's Kodi interface or any streaming platform. Thank you!

Current copacetic version 2.4.4. Just checked for updates and there is nothing new, interface for updates a bit confusing I wish detail menu was more functional, like all of the option would be on the screen, that would be perfect. Will try to check new version tomorrow

**Comment by realcopacetic** [comment]
> > Hi, when you say 'pause menu' do you mean the controls (play button, back, forward, rewind etc)? Those should already auto-hide. Some others have had the issue where the OSD doesn't autohide, It seems confined to certain platforms, are you by any chance on LIbreElec?
> 
> No I don't use LIbreElec
> I use Kodi on TCL Google TV and hands down copacetic is best looking interface list for movies and billboard for TV show I ever seen whether it's Kodi interface or any streaming platform. Thank you!
> 
> Current copacetic version 2.4.4. Just checked for updates and there is nothing new, interface for updates a bit confusing I wish detail menu was more functional, like all of the option would be on the screen, that would be perfect. Will try to check new version tomorrrow

Thanks I'm glad you like it! Update is only currently available on my repo. I'll push it to the official Kodi repo shortly, hopefully that will fix the issue

**Comment by realcopacetic** [comment]
marking as closed unless someone reports it's still an issue. The new method uses the skin timer approach the same as Estuary

**Comment by uaxpasha** [comment]
Hey, sorry for no feedback. 
Just checked on 2.6.1 
Clicked open OSD menu 
clicked pause, 
Clicked play
OSD menu did not hide

I forgot abouth the issue because I changed return button to 'play/pause', instead of default 'show OSD menu' to press pause and forgot about the issue.
