### ISSUE TITLE
Fast forward menu does not show up on progress bar

### ISSUE THREAD

**Issue by uaxpasha** [realcopacetic/skin.copacetic#198]
Copacetic 2.6.1 Google TV TCL
I have changed settings so I only rewind +10 sec or -10 sec

Whether I click once or several times to fast forward/backward or whether I hold the button to to fast forward/backward progress bar does not show to which point it will jump.

Also, its probably unrelated to this bug but info about how much was fast forward (+10 then +20 then +30) will disappear after 2 seconds which is not convenient when you do it for more then 2 seconds.

https://github.com/user-attachments/assets/cc8b2a4c-47c1-491a-8daa-9ec7a8c88684

**Comment by realcopacetic** [comment]
Thanks will check this out

**Comment by realcopacetic** [comment]
Fixed in 2.66 thanks
