### ISSUE TITLE
missing time stamp duration on playback 

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#200]
The duration and current position of the playback bar are missing.

**Comment by realcopacetic** [comment]
Do you mean for PVR? Can you clarify a bit more what's missing?

**Comment by pasnox** [comment]
no, it's when I do play a network stream. See attached screenshot 
![IMG_20241007_084640.jpg](https://github.com/user-attachments/assets/63537c80-a6ca-433e-b15d-60dbc2e89f8a)
Note that everything is fine with Estuary with the same stream.

**Comment by realcopacetic** [comment]
Thanks. I've never done network streams before so hadn't tested that use case. Fixed in 2.6.6
