### ISSUE TITLE
Dependency Error when trying to install 1.1.4 from Kodi & Copacetic repo

### ISSUE THREAD

**Issue by thereisnoanderson** [realcopacetic/skin.copacetic#21]
Hi
great work of yours!
Unfortunate I am having a Dependency Error on Linux and Android for visualization.waveform and it doesnt matter what repo I use (Kodi or realcopacetic.github.io) there is no source to install that. A kodi.tv addons lookup reveals that there is no Linux Platform support for that addon
Hope you can share fix for that, that would be great :)

thank you

**Comment by realcopacetic** [comment]
Thanks for pointing this out. I wasn't aware that this visualisation was missing on Linux. For now I have updated the version of the skin on my repo (realcopacetic.github.io) to remove this dependency. Please try again (v 1.1.5) and let me know if you run into any problems.
