### ISSUE TITLE
PVR support

### ISSUE THREAD

**Issue by realcopacetic** [realcopacetic/skin.copacetic#26]

**Comment by pasnox** [comment]
Hey,

As a new Freebox* user, I now need PVR/TV support in Kodi. Forcing me to temporarily go back to Kodi default theme. What's the status here, is there anything testable?

* Freebox is a triple play offer which provides a router for the internet, telephone and networked TV.

Thanks

**Comment by realcopacetic** [comment]
hi, it's a bit of a work in progress at the moment. I've added very MVP tv guide and channel lists views. You should be able to see these if you add shortcuts to these areas in your menu.

**Comment by pasnox** [comment]
Hey, TV & Guide works, minimalist but will allow me back on this theme 😁

**Comment by realcopacetic** [comment]
> Hey, TV & Guide works, minimalist but will allow me back on this theme 😁
> 

Yep very minimalist. I don't have a good comparison as I haven't got a full featured IPTV service set up. Can you let me know the things that are missing so I know what to prioritise? Direction of PVR skin development will probably be more community-driven as I don't use it

**Comment by pasnox** [comment]
- Make it bigger (Fullscreen)
- Use alternate captions (Use Divertissement if program name is missing)
- Better program progress bar

![IMG20240603180552.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/7fe86ca1-4c09-45b9-ad9d-7c4f3c421de3)

**Comment by pasnox** [comment]
- Make it bigger (Fullscreen)
- Use TV like left panel (current program and progress)
- Enlarge bottom description, it's barely readable from sofa

![IMG20240603180923.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/5ce3d7db-685d-4b81-8cfd-d5b9f00871c4)

**Comment by pasnox** [comment]
- Add channel name/ Logo
- Add program time/duration 
- Bigger description 

![IMG20240603182207.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/8e81fc69-7297-4555-bb81-be4e1acf0acd)

**Comment by pasnox** [comment]
Hey, any progress here?

**Comment by pasnox** [comment]
Do suggestions get implemented or do I need to dump them into another issue?

**Comment by realcopacetic** [comment]
I think most of them should now be live in 2.6.4. There's an alternative view on Channels if you press left and switch from simple to detailed. If you feel anything isn't right or can be improved, please open it as a new issue, thanks
