### ISSUE TITLE
Skip step/seeking numerical and bar reference

### ISSUE THREAD

**Issue by realcopacetic** [realcopacetic/skin.copacetic#32]
https://forum.kodi.tv/showthread.php?tid=373114&pid=3157705#pid3157705

RFE: Skip step/seeking numerical and bar reference. Something similar to your RW/FF OSD would be nice perhaps optioned in the customizations settings section. Could also just be added to the seek bar since the bar appears when skip stepping anyway. Right now I'm navigating blindly when clicking the directional buttons multiple times.

**Comment by realcopacetic** [comment]
Added in 1.1.16 - keeping open as needs more testing/refinement

**Comment by mmanuxx** [comment]
Thanks for adding this. The Up & Down arrow skip step (default 10 min) OSD works well. The forward/backward right/left arrow skip step OSD is inconsistent. Seems like it doesn`t always have enough time to appear before it automatically disappears. So it flashes very quickly barely decipherable.

**Comment by realcopacetic** [comment]
Yep I noticed that - will refine it shortly, thanks for the feedback

**Comment by realcopacetic** [comment]
hi @mmanuxx it appears that the thing with the short skip step being very quick before disappearing is a Kodi issue. It doesn't matter how long I display the label for, it disappears because the actual value of the label appears to be cleared by Kodi after that short interval. I've observed the same behaviour in Estuary and tested by having a label that is always carrying this value, then falling back to a test string when the vlaue is not present and it will only ever show the skip value for that brief window of time. 

I'll mark this as closed therefore, thanks!
