### ISSUE TITLE
Pause Menu contains wrong description

### ISSUE THREAD

**Issue by freijon** [realcopacetic/skin.copacetic#34]
In the top row of the pause menu (when playing music) there is a wrong button description:

The button on the top left left is called "Pause" but should be "Back"

**Comment by realcopacetic** [comment]
Can you share a screenshot of what you mean please

**Comment by freijon** [comment]
https://imgur.com/a/Z92KkmY

The left arrow is selected, but the text in the top left corner says "Pause" instead of "Back"

**Comment by realcopacetic** [comment]
Thanks will check it out

**Comment by realcopacetic** [comment]
Fixed, will push update in next few days, thanks
