### ISSUE TITLE
Album cover doesn't always display correctly

### ISSUE THREAD

**Issue by freijon** [realcopacetic/skin.copacetic#36]
I'm using the [Deezer Addon](https://github.com/Valentin271/DeezerKodi) to stream music on Kodi. Unfortunately with Copacetic the album cover is not shown in the fullscreen music osd.

This works fine with other skins like Estuary.

It also works fine with Copacetic and my local music library. Only when using Deezer with Copacetic is the album cover gone.

**Comment by realcopacetic** [comment]
I'll check it out, I don't use many plugins so haven't tested much

**Comment by realcopacetic** [comment]
@freijon Can you confirm if this is an issue with all information being hidden (and it appears when you press the info button or i) or is it specifically about the album artwork?

Unfortunately it looks like the Deezer addon you linked to only works if you have a paid account and I don't have one so I can't test.

**Comment by freijon** [comment]
I confirm it's only the album cover. The rest of the info is shown correctly.

**Comment by realcopacetic** [comment]
Issue identified. Will replace Player.Art(thumb) with MusicPlayer.Cover. Fix coming in next version
