### ISSUE TITLE
Can't select image as a background under Main Menu

### ISSUE THREAD

**Issue by TheOne988** [realcopacetic/skin.copacetic#38]
In the official repo skin (version 1.1.4) even on the latest version from github (version 1.1.6) when you go to the menu settings and try to set a background for any available menu you get NONE (screenshot bellow)

Example:
GENREAL > HOME MENU > MOVIES > Select Background -> None

Basically it is missing the menu for Single image, Multiple images...

I'm using LibreElec 11.0.1 but have also tried Kodi 20.2 from flathub but the same behavior persists. 

If you need any additional info I will be happy to provide.

![screenshot00000](https://github.com/realcopacetic/skin.copacetic/assets/36518440/8d49e5bc-8dca-44fe-af1f-e1f4db5c08c8)

**Comment by realcopacetic** [comment]
This also sounds like an issue with your skin.shortcuts as Copacetic is just displaying the window that skin.shortcuts creates here, which should have options for Single image, Multi-image, any smart video playlists you've added and the skin playlists provided by Copacetic.

I would try reinstalling skin.shortcuts, as it sounds like something is up with it on your system.

**Comment by TheOne988** [comment]
If you think this issue is related with `Power menu not working properly #39 ` I will close this one as duplicate.

**Comment by realcopacetic** [comment]
I'm not sure. Let's keep it open for now and I'll try and see if I've done something wrong in the copacetic implementation of skin shortcuts

**Comment by realcopacetic** [comment]
Fixed, see: https://github.com/realcopacetic/skin.copacetic/issues/39
