### ISSUE TITLE
[Bug] Player Info Screen On Pause

### ISSUE THREAD

**Issue by starman2908** [realcopacetic/skin.copacetic#42]
Hiya, hope this message finds you well, I Just got a chance to test the latest version (1.1.7) and noticed a bug. On playback pause i'm no longer getting the info screen (The one with clearlogo, plot etc). Are you able to replicate this?  

Btw thanks for the work you did on the grid view for video add-ons, that was super quick and looks great, had a hectic few days at work so today has been my first chance to sit down and update to go through... i think i have a couple of ideas if it's okay for me to open up a new [enhancement] issue?

![screenshot00005](https://github.com/realcopacetic/skin.copacetic/assets/36766279/70abb568-931e-4c81-9efb-2e244e39eec2)

**Comment by realcopacetic** [comment]
Sorry yes I made a typo, it will be fixed in next version 1.1.8, which should go live on August 4th

**Comment by realcopacetic** [comment]
Yes feel free to open any enhancement requests you have thanks!

**Comment by realcopacetic** [comment]
fixed in 1.1.10
