### ISSUE TITLE
Overrides.xml is still with first uppercase letter instead of lowercase one

### ISSUE THREAD

**Issue by TheOne988** [realcopacetic/skin.copacetic#43]
The file `skin.copacetic/shortcuts/Overrides.xml` is with upper case first letter when you install the skin via the repository although the file is with lower case on the GitHub page `skin.copacetic/shortcuts/overrides.xml`.
This cause the same problem for skin.shortcuts not to work properly on Linux.

Install directory preview:
![image](https://github.com/realcopacetic/skin.copacetic/assets/36518440/4af7d899-3901-46e5-a9c3-98de69d5986b)

GitHub directory preview:
![image](https://github.com/realcopacetic/skin.copacetic/assets/36518440/5eb83c46-6498-4800-830d-941f327515b5)

**FIX: the zip file that provides the latest updates from the repo skin.copacetic-1.1.7.zip contains the `Overrides.xml` file with first uppercase letter. - needs to be updated from the main repo "Master" branch.
Link to the affected zip file:** https://github.com/realcopacetic/realcopacetic.github.io/blob/master/repo/zips/skin.copacetic/skin.copacetic-1.1.7.zip

**Comment by realcopacetic** [comment]
Hi, I'll push the latest version with this update (1.1.8) to my repository hopefullly tonight, thanks

**Comment by realcopacetic** [comment]
fixed in 1.1.8
