### ISSUE TITLE
ShutDown menu Add-ons button not working

### ISSUE THREAD

**Issue by TheOne988** [realcopacetic/skin.copacetic#44]
The hard-coded Add-ons button from shutdown menu is not working it returns the fallowing error when pressed:
`info <general>: Activate of window '10040' refused because there are active modal dialogs`

**FIX for the issue:**
In the file `skin.copacetic/shortcuts/shutdownmenu.DATA.xml` the `<label>$LOCALIZE[24001]</label>` should be replaced with `<label>$LOCALIZE[10140]</label>`.

Non-working ID **24001** -> Working ID **10140**

Source: https://kodi.wiki/view/Window_IDs - **Windows IDs - Kodi**

**Comment by realcopacetic** [comment]
fixed 1.1.8
