### ISSUE TITLE
File Manager - Add network location... not working

### ISSUE THREAD

**Issue by TheOne988** [realcopacetic/skin.copacetic#46]
When you try to open the "Add network location.." menu from the File Manager nothing happens. It looks like it opens the window but it is not focused because you cannot do anything until you hit Backspace to exit the "invisible" window.

`Window: networksetup (DialogSettings.xml)`
`Mouse: (1548,846) Focused: -80 (spincontrolex)`

Couldn't find anything specific in the skin files. Was looking for `Window.IsVisible(networksetup)` but I may be totally off track for this bug.

Here is a short video of this behavior:

https://github.com/realcopacetic/skin.copacetic/assets/36518440/2bd0fb7c-23ea-45ab-b05f-c7e480742581

**Comment by realcopacetic** [comment]
Thanks, I had a conflicting visibility condition. Will include this fix in 1.1.8 which I'll push to my repo tonight and to official repo shortly

**Comment by realcopacetic** [comment]
Fixed in 1.1.8
