### ISSUE TITLE
[Feature Request] Abbility for the music player to stay focused

### ISSUE THREAD

**Issue by TheOne988** [realcopacetic/skin.copacetic#53]
Hi @realcopacetic,

is it possible for the music player to stay visible all the time or at least to be optional. Because I think that you have made a super interface for the music player and  it is pity to be hidden all the time.

![screenshot00002](https://github.com/realcopacetic/skin.copacetic/assets/36518440/d484ef35-d099-44fc-99c5-e6b2b981ed94)

**Comment by realcopacetic** [comment]
Hi @TheOne988 - It's user definable already (this is Kodi built-in behaviour).

Press info and it will appear and stay up. Press it again and it will only show for the first few seconds and then for a few seconds on each song change.

**Comment by TheOne988** [comment]
Sh.. how did I miss that.

Thanks for the info...

**Comment by realcopacetic** [comment]
Haha I only recently discovered this myself when someone was asking why the info didn't disappear so they could see their visualisation in the background!
