### ISSUE TITLE
Resolution in breadcrumbs info in grid view

### ISSUE THREAD

**Issue by randomragenet** [realcopacetic/skin.copacetic#63]
Enhancement request:
Add video resolution as an option for breadcrumb display in grid view.

Currently when using grid view, the only way to see what resolution videos are in is to open the info display. It would be useful if video resolution could be added to the breadcrumb display when a title is hovered, either before or after the movie date.

Copacetic is GORGEOUS, by the way, and after getting it configured the way I want, I legitimately want to invite people over to show it off.

**Comment by realcopacetic** [comment]
Thanks for the feedback, glad you like it! Let me see about adding that in

**Comment by realcopacetic** [comment]
Added in 1.1.12
