### ISSUE TITLE
Option to turn off star ratings

### ISSUE THREAD

**Issue by randomragenet** [realcopacetic/skin.copacetic#64]
Enhancement request:
Option to turn off star ratings in movie info screen either per view or universally

I don't even know where these star ratings came from. They're not mine.

**Comment by realcopacetic** [comment]
If there is no user rating, it pulls from wherever your scraper is set to pull it from, usually tmdb or IMDb. I can add an option to disable, no probs

**Comment by realcopacetic** [comment]
Added option to disable, 1.1.12
