### ISSUE TITLE
Bug: OSD settings timeout too fast

### ISSUE THREAD

**Issue by randomragenet** [realcopacetic/skin.copacetic#65]
The timeout for the OSD settings is way too quick. The menu will fade before the user can make a selection if they don't press a button for ~2 seconds.

If you're trying to adjust subtitles or audio channels, the menu will disappear before you can make a selection.

**Comment by realcopacetic** [comment]
Thanks for the feedback, do you think it would be better to have it longer just on those screens or, say, five seconds everywhere?

**Comment by realcopacetic** [comment]
Disabled osd autoclose if another window is open on top of OSD controls. Added - 1.1.12
