### ISSUE TITLE
Bug: PG-13 logo on movie start toast improperly spaced

### ISSUE THREAD

**Issue by randomragenet** [realcopacetic/skin.copacetic#70]
When playing a PG-13 rated movie, the toast at movie start is improperly spaced

When copacetic is set to US ratings, and a PG-13 movie is started, the informational toast that appears in the top left corner of the screen doesn't leave enough space around the PG-13 logo, so the words in the toast run into the logo.

**Comment by realcopacetic** [comment]
Fixed in 1.1.14
