### ISSUE TITLE
Feature request: Chapter indicators in movie timeline

### ISSUE THREAD

**Issue by randomragenet** [realcopacetic/skin.copacetic#71]
Currently, the video timeline is just one solid progress bar. I love copacetic's minimalist aesthetic, but it would be really nice to have a visual indicator of how many chapters there are in the video.

It could be something as simple as breaks in the progress bar. Or a small bit of text above the progress bar that says "Chapter X/Y"

**Comment by realcopacetic** [comment]
Added in 1.1.14
