### ISSUE TITLE
The shutdown menu is difficult to access with a CEC TV remote

### ISSUE THREAD

**Issue by berettavexee** [realcopacetic/skin.copacetic#90]
This ticket is a request for enhancement, to enter the shutdown menu you have to hold down the return button for half a second. My TV remote doesn't support key-holding. It is therefore not possible to use this remote to access the shutdown menu and shutdown the device. I assume that this is not an isolated case.

It might be interesting to offer a second way of accessing the shutdown menu that is compatible with CEC remotes.

**Comment by realcopacetic** [comment]
Hi, I've added an option in skin settings to place a shortcut to the shutdown menu in the hidden views menu that is accessible from all the main windows. You can find this under Settings > Copacetic > Views > 'Add shutdown menu shortcut to hidden views menu'. This will be available in 1.1.17. 

It might be a little while until I push an update to the main Kodi repository as I just did one yesterday, but I can push this to my repo probably in the next 2-3 days. So if you enable your addons to be updated from third-party sources, you'll be able to see this update sooner.

Details of my repo are in the first post here: https://forum.kodi.tv/showthread.php?tid=373114

As long as you install my repo and enable third-party sources for addon updates, it should update to 1.1.7 as soon as it's available

**Comment by realcopacetic** [comment]
Added in 1.1.17
